// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScalaPOS.Data;

#nullable disable

namespace ScalaPOS.Migrations
{
    [DbContext(typeof(PosDbContext))]
    [Migration("20260302201846_AddAppointmentsModule")]
    partial class AddAppointmentsModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ScalaPOS.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowManualEntry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystemAccount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountType = "Asset",
                            AllowManualEntry = true,
                            Code = "1000",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemAccount = true,
                            Name = "Cash on Hand",
                            SubType = "Current Asset"
                        },
                        new
                        {
                            Id = 2,
                            AccountType = "Asset",
                            AllowManualEntry = false,
                            Code = "1010",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemAccount = true,
                            Name = "Cash in Bank",
                            SubType = "Current Asset"
                        },
                        new
                        {
                            Id = 3,
                            AccountType = "Asset",
                            AllowManualEntry = false,
                            Code = "1100",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemAccount = true,
                            Name = "Accounts Receivable",
                            SubType = "Current Asset"
                        },
                        new
                        {
                            Id = 4,
                            AccountType = "Asset",
                            AllowManualEntry = false,
                            Code = "1200",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemAccount = true,
                            Name = "Inventory",
                            SubType = "Current Asset"
                        },
                        new
                        {
                            Id = 5,
                            AccountType = "Liability",
                            AllowManualEntry = false,
                            Code = "2000",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemAccount = true,
                            Name = "Accounts Payable",
                            SubType = "Current Liability"
                        },
                        new
                        {
                            Id = 6,
                            AccountType = "Liability",
                            AllowManualEntry = false,
                            Code = "2100",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemAccount = true,
                            Name = "Sales Tax Payable",
                            SubType = "Current Liability"
                        },
                        new
                        {
                            Id = 7,
                            AccountType = "Equity",
                            AllowManualEntry = false,
                            Code = "3000",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemAccount = true,
                            Name = "Owner's Equity",
                            SubType = "Equity"
                        },
                        new
                        {
                            Id = 8,
                            AccountType = "Revenue",
                            AllowManualEntry = false,
                            Code = "4000",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemAccount = true,
                            Name = "Sales Revenue",
                            SubType = "Operating Revenue"
                        },
                        new
                        {
                            Id = 9,
                            AccountType = "Expense",
                            AllowManualEntry = false,
                            Code = "5000",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemAccount = true,
                            Name = "Cost of Goods Sold",
                            SubType = "Cost of Sales"
                        },
                        new
                        {
                            Id = 10,
                            AccountType = "Expense",
                            AllowManualEntry = true,
                            Code = "6000",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemAccount = true,
                            Name = "Wages Expense",
                            SubType = "Operating Expense"
                        },
                        new
                        {
                            Id = 11,
                            AccountType = "Expense",
                            AllowManualEntry = true,
                            Code = "6100",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemAccount = false,
                            Name = "Rent Expense",
                            SubType = "Operating Expense"
                        });
                });

            modelBuilder.Entity("ScalaPOS.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PartySize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StaffId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending");

                    b.Property<int?>("TableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("ScalaPOS.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetKdsStation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#FF6B6B",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Food items",
                            DisplayOrder = 1,
                            Icon = "🍔",
                            IsActive = true,
                            Name = "Food",
                            TargetKdsStation = "Kitchen"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#4ECDC4",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Drinks and beverages",
                            DisplayOrder = 2,
                            Icon = "☕",
                            IsActive = true,
                            Name = "Beverages",
                            TargetKdsStation = "Kitchen"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#FFE66D",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sweet treats",
                            DisplayOrder = 3,
                            Icon = "🍰",
                            IsActive = true,
                            Name = "Desserts",
                            TargetKdsStation = "Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#95E1D3",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Starters",
                            DisplayOrder = 4,
                            Icon = "🍤",
                            IsActive = true,
                            Name = "Appetizers",
                            TargetKdsStation = "Kitchen"
                        });
                });

            modelBuilder.Entity("ScalaPOS.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastVisit")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("TEXT");

                    b.Property<string>("MembershipTier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalSpent")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VisitCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john@example.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Doe",
                            LoyaltyPoints = 250,
                            MemberSince = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipTier = "Gold",
                            Phone = "5551234567",
                            TotalSpent = 1250.00m,
                            VisitCount = 25
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Ave",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1985, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jane@example.com",
                            FirstName = "Jane",
                            IsActive = true,
                            LastName = "Smith",
                            LoyaltyPoints = 150,
                            MemberSince = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MembershipTier = "Silver",
                            Phone = "5551234568",
                            TotalSpent = 750.00m,
                            VisitCount = 15
                        });
                });

            modelBuilder.Entity("ScalaPOS.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastRestocked")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("ScalaPOS.Models.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPosted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCredit")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDebit")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("ScalaPOS.Models.JournalLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Credit")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Debit")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("JournalEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("JournalEntryId");

                    b.ToTable("JournalLines");
                });

            modelBuilder.Entity("ScalaPOS.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Discount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PointsDiscountAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsRedeemed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StaffId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TableNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Tax")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StaffId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ScalaPOS.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ScalaPOS.Models.OrderPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderPayments");
                });

            modelBuilder.Entity("ScalaPOS.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaxClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "",
                            CategoryId = 1,
                            CostPrice = 5.50m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic beef burger with cheese",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Burger Deluxe",
                            Price = 12.99m,
                            SKU = "FOOD-001",
                            StockQuantity = 50,
                            TaxClass = ""
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "",
                            CategoryId = 1,
                            CostPrice = 4.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh romaine with caesar dressing",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Caesar Salad",
                            Price = 9.99m,
                            SKU = "FOOD-002",
                            StockQuantity = 30,
                            TaxClass = ""
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "",
                            CategoryId = 1,
                            CostPrice = 6.50m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic pizza with mozzarella",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Margherita Pizza",
                            Price = 15.99m,
                            SKU = "FOOD-003",
                            StockQuantity = 25,
                            TaxClass = ""
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "",
                            CategoryId = 2,
                            CostPrice = 0.80m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Strong Italian coffee",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Espresso",
                            Price = 3.50m,
                            SKU = "BEV-001",
                            StockQuantity = 100,
                            TaxClass = ""
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "",
                            CategoryId = 2,
                            CostPrice = 1.50m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Freshly squeezed",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Orange Juice",
                            Price = 4.99m,
                            SKU = "BEV-002",
                            StockQuantity = 40,
                            TaxClass = ""
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "",
                            CategoryId = 3,
                            CostPrice = 2.50m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rich chocolate layer cake",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Chocolate Cake",
                            Price = 6.99m,
                            SKU = "DES-001",
                            StockQuantity = 20,
                            TaxClass = ""
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "",
                            CategoryId = 4,
                            CostPrice = 3.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Crispy vegetable rolls",
                            ImageUrl = "",
                            IsActive = true,
                            Name = "Spring Rolls",
                            Price = 7.99m,
                            SKU = "APP-001",
                            StockQuantity = 35,
                            TaxClass = ""
                        });
                });

            modelBuilder.Entity("ScalaPOS.Models.RestaurantTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Angle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GuestCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(80);

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionY")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SeatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ServerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Shape")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(80);

                    b.HasKey("Id");

                    b.ToTable("RestaurantTables", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Angle = 0,
                            Capacity = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Height = 80,
                            IsActive = true,
                            IsLocked = false,
                            Name = "T1",
                            PositionX = 60,
                            PositionY = 60,
                            Section = "Indoor",
                            Shape = "square",
                            Status = "available",
                            Width = 80
                        },
                        new
                        {
                            Id = 2,
                            Angle = 0,
                            Capacity = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Height = 80,
                            IsActive = true,
                            IsLocked = false,
                            Name = "T2",
                            PositionX = 200,
                            PositionY = 60,
                            Section = "Indoor",
                            Shape = "square",
                            Status = "occupied",
                            Width = 80
                        },
                        new
                        {
                            Id = 3,
                            Angle = 0,
                            Capacity = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Height = 80,
                            IsActive = true,
                            IsLocked = false,
                            Name = "T3",
                            PositionX = 360,
                            PositionY = 60,
                            Section = "Indoor",
                            Shape = "rectangle",
                            Status = "reserved",
                            Width = 80
                        },
                        new
                        {
                            Id = 4,
                            Angle = 0,
                            Capacity = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Height = 80,
                            IsActive = true,
                            IsLocked = false,
                            Name = "T4",
                            PositionX = 60,
                            PositionY = 200,
                            Section = "Indoor",
                            Shape = "circle",
                            Status = "available",
                            Width = 80
                        },
                        new
                        {
                            Id = 5,
                            Angle = 0,
                            Capacity = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Height = 80,
                            IsActive = true,
                            IsLocked = false,
                            Name = "T5",
                            PositionX = 200,
                            PositionY = 200,
                            Section = "Indoor",
                            Shape = "square",
                            Status = "occupied",
                            Width = 80
                        },
                        new
                        {
                            Id = 6,
                            Angle = 0,
                            Capacity = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Height = 80,
                            IsActive = true,
                            IsLocked = false,
                            Name = "T6",
                            PositionX = 360,
                            PositionY = 200,
                            Section = "Indoor",
                            Shape = "rectangle",
                            Status = "available",
                            Width = 80
                        },
                        new
                        {
                            Id = 7,
                            Angle = 0,
                            Capacity = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Height = 80,
                            IsActive = true,
                            IsLocked = false,
                            Name = "P1",
                            PositionX = 60,
                            PositionY = 60,
                            Section = "Outdoor",
                            Shape = "circle",
                            Status = "available",
                            Width = 80
                        },
                        new
                        {
                            Id = 8,
                            Angle = 0,
                            Capacity = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Height = 80,
                            IsActive = true,
                            IsLocked = false,
                            Name = "P2",
                            PositionX = 200,
                            PositionY = 60,
                            Section = "Outdoor",
                            Shape = "circle",
                            Status = "occupied",
                            Width = 80
                        },
                        new
                        {
                            Id = 9,
                            Angle = 0,
                            Capacity = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Height = 80,
                            IsActive = true,
                            IsLocked = false,
                            Name = "P3",
                            PositionX = 60,
                            PositionY = 200,
                            Section = "Outdoor",
                            Shape = "rectangle",
                            Status = "available",
                            Width = 80
                        },
                        new
                        {
                            Id = 10,
                            Angle = 0,
                            Capacity = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Height = 80,
                            IsActive = true,
                            IsLocked = false,
                            Name = "B1",
                            PositionX = 60,
                            PositionY = 60,
                            Section = "Bar",
                            Shape = "circle",
                            Status = "available",
                            Width = 80
                        });
                });

            modelBuilder.Entity("ScalaPOS.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("ScalaPOS.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PINCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@scalapos.com",
                            EmployeeId = "EMP001",
                            FirstName = "Admin",
                            HireDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HourlyRate = 25.00m,
                            IsActive = true,
                            LastName = "User",
                            PINCode = "1234",
                            Phone = "1234567890",
                            ProfileImage = "",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manager@scalapos.com",
                            EmployeeId = "EMP002",
                            FirstName = "Manager",
                            HireDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HourlyRate = 20.00m,
                            IsActive = true,
                            LastName = "Smith",
                            PINCode = "5678",
                            Phone = "1234567891",
                            ProfileImage = "",
                            Role = "manager"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "cashier@scalapos.com",
                            EmployeeId = "EMP003",
                            FirstName = "Cashier",
                            HireDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HourlyRate = 15.00m,
                            IsActive = true,
                            LastName = "Jones",
                            PINCode = "9012",
                            Phone = "1234567892",
                            ProfileImage = "",
                            Role = "cashier"
                        });
                });

            modelBuilder.Entity("ScalaPOS.Models.Appointment", b =>
                {
                    b.HasOne("ScalaPOS.Models.RestaurantTable", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Table");
                });

            modelBuilder.Entity("ScalaPOS.Models.InventoryItem", b =>
                {
                    b.HasOne("ScalaPOS.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ScalaPOS.Models.JournalLine", b =>
                {
                    b.HasOne("ScalaPOS.Models.Account", "Account")
                        .WithMany("JournalLines")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScalaPOS.Models.JournalEntry", "JournalEntry")
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("ScalaPOS.Models.Order", b =>
                {
                    b.HasOne("ScalaPOS.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.HasOne("ScalaPOS.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId");

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("ScalaPOS.Models.OrderItem", b =>
                {
                    b.HasOne("ScalaPOS.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScalaPOS.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ScalaPOS.Models.OrderPayment", b =>
                {
                    b.HasOne("ScalaPOS.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ScalaPOS.Models.Product", b =>
                {
                    b.HasOne("ScalaPOS.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ScalaPOS.Models.Shift", b =>
                {
                    b.HasOne("ScalaPOS.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("ScalaPOS.Models.Account", b =>
                {
                    b.Navigation("JournalLines");
                });

            modelBuilder.Entity("ScalaPOS.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ScalaPOS.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ScalaPOS.Models.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("ScalaPOS.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
